name: Continuous Integration - Deploy

on:
  push:
    branches: [ "main" ]

# Secrets:
#   AWS_REGION: "us-east-1"
#   AWS_BUCKET_NAME: "example-bucket"
#   AWS_UPLOAD_ROLE_ARN: "arn:aws:iam::1234567890:role/example-role"
#   AWS_CLOUDFRONT_DISTRIBUTION_ID: "E1C4SMKLBYI8C9"

permissions:
  id-token: write   # This is required for requesting the JWT for AWS Actions
  contents: read    # This is required for actions/checkout for AWS Actions

jobs:
  call-build:
    uses: balassy/resume-frontend/.github/workflows/build.yml@main
    secrets: inherit

  deploy:
    needs: call-build

    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: Build output
        path: dist
    - name: View build artifacts
      run: ls -R
      working-directory: dist
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_UPLOAD_ROLE_ARN }}
        role-session-name: ResumeUploadSession
        aws-region: ${{ secrets.AWS_REGION }}
    - name:  Upload artifacts to S3
      run: aws s3 sync ./dist s3://${{ secrets.AWS_BUCKET_NAME }}/
    - name: Invalidate CloudFront cache
      run: |
        CLOUDFRONT_INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*' --query Invalidation.Id)
        echo "CLOUDFRONT_INVALIDATION_ID=$CLOUDFRONT_INVALIDATION_ID" >> $GITHUB_ENV
    - name: Wait until CloudFront invalidation completed
      run: aws cloudfront wait invalidation-completed --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --id ${{ env.CLOUDFRONT_INVALIDATION_ID }}
