name: Continuous Integration - Build

on:
  push:
    branches-ignore: main
  workflow_call:

# Secrets:
#   GOOGLE_ANALYTICS_ID: "G-XXXXXXXXXX"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      env:
        GOOGLE_ANALYTICS_ID: "${{ secrets.GOOGLE_ANALYTICS_ID }}"
      run: npm run build
    - name: Test
      run: npm test
    - name: Create version file
      run: |
        date > dist/version.txt
        cat dist/version.txt
    - name: Run UI tests locally
      uses: cypress-io/github-action@v5
      with:
        install: false
        start: npm start
        wait-on: 'http://localhost:3000'
        config-file: cypress.config.local.ts
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build output
        path: dist/
