name: Continuous Integration - Deploy

on:
  push:
    branches: [ "main" ]

# Secrets for Staging and Production environments:
#   AWS_REGION: "us-east-1"
#   AWS_BUCKET_NAME: "example-bucket"
#   AWS_UPLOAD_ROLE_ARN: "arn:aws:iam::1234567890:role/example-role"
#   AWS_CLOUDFRONT_DISTRIBUTION_ID: "E1C4SMKLBYI8C9"

permissions:
  id-token: write   # This is required for requesting the JWT for AWS Actions
  contents: read    # This is required for actions/checkout for AWS Actions

jobs:
  call-build:
    uses: balassy/resume-frontend/.github/workflows/build.yml@main
    secrets: inherit

  call-deploy-to-staging:
    uses: balassy/resume-frontend/.github/workflows/deploy-to-environment.yml@main
    secrets: inherit
    needs: call-build
    with:
      target_environment: Staging

  call-deploy-to-production:
    uses: balassy/resume-frontend/.github/workflows/deploy-to-environment.yml@main
    secrets: inherit
    needs: call-deploy-to-staging
    with:
      target_environment: Production
